[package]
name = "rust_learning"
version = "0.1.0"
authors = ["liya2017 <Liya@cryptape.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
[dependencies]
rand = "0.8.3"
